language: node_js

node_js: 'lts/*'

cache:
  directories:
    - 'node_modules'

before_script:
  - npx audit-ci --low

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_AUTH_TOKEN'
  skip_cleanup: true
  on:
    tags: true
